### ISSUE TITLE
how to convert .symbols file to .dSYM file 

### ISSUE THREAD

**Issue by tobefuturer** [NickAger/iOSSymbolParsing#1]
Is this tool can convert .symbols to .dSYM file?
I miss my dsym file, but I have saved the .symbols file. So I want to find a tool to rebuild .dSYM file from .symbols file. Can this tool do? Or other tool?

Thanks~

**Comment by NickAger** [comment]
No it converts .symbol files into an easy to parse JSON format see https://github.com/NickAger/iOSSymbolParsing/blob/master/README.md

I don't know of other tools that would do what you want. Sorry.
